name: release

on:
  release:
    types:
      - created


jobs:
  release-job:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
        pip install twine wheel
    - name: Run tests
      run: |
        pytest --cov=./apache_airflow_flowitems --cov-report xml --cov-report term-missing .
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Check version number match
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        # Make sure the package version is the same as the tag
        grep -Rq "^Version: ${GITHUB_REF:11}$" apache_airflow_flowitems.egg-info/PKG-INFO
    - name: Publish to PyPI
      run: |
        twine check dist/*
        twine upload --repository pypi --username __token__ --password ${PYPI_TOKEN} dist/*
    - name: Test installation
      run: |
        sleep 120
        pip install apache-airflow-flowitems==${GITHUB_REF:11}
